#!/usr/bin/env python3
"""Generate v8 CNBE-32 RISC-V skill tables from data/cnbe32.db."""

import hashlib
import json
import os
import sqlite3
import struct

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
V8_DIR = os.path.dirname(TOOLS_DIR)
REPO_DIR = os.path.dirname(os.path.dirname(V8_DIR))
DB_PATH = os.path.join(REPO_DIR, "data", "cnbe32.db")
OUT_DIR = os.path.join(V8_DIR, "generated")


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    rows = con.execute(
        "select unicode, cnbe, track from cnbe32 order by unicode, rowid"
    ).fetchall()
    con.close()

    all_rows = [(u, c, t) for u, c, t in rows]
    std_rows = [(u, c, t) for u, c, t in rows if t == "standard"]
    n_duplicates = len(all_rows) - len({c for _, c, _ in all_rows})

    def write_bin(name: str, data_rows: list) -> str:
        path = os.path.join(OUT_DIR, name)
        with open(path, "wb") as fh:
            for u, c, _ in data_rows:
                fh.write(struct.pack("<II", u, c))
        return path

    def write_hex(name: str, values: list) -> str:
        path = os.path.join(OUT_DIR, name)
        with open(path, "w", encoding="ascii") as fh:
            for v in values:
                fh.write(f"{v:08X}\n")
        return path

    all_bin = write_bin("skill_table.bin", all_rows)
    std_bin = write_bin("skill_table_8105.bin", std_rows)
    unicode_hex = write_hex("unicode_table.hex", [u for u, _, _ in all_rows])
    cnbe_hex = write_hex("cnbe_table.hex", [c for _, c, _ in all_rows])

    cc_path = os.path.join(OUT_DIR, "cnbe_skill_table.cc")
    with open(cc_path, "w", encoding="ascii") as fh:
        fh.write("// Generated by tools/gen_skill_table.py from data/cnbe32.db\n")
        fh.write("#include \"cnbe_skill_table.h\"\n\n")
        fh.write(f"const uint32_t cnbe_unicode_table[CNBE_TABLE_SIZE] = {{\n")
        for i in range(0, len(all_rows), 8):
            chunk = [str(u) for u, _, _ in all_rows[i : i + 8]]
            fh.write("    " + ", ".join(chunk) + ",\n")
        fh.write("};\n\n")
        fh.write(f"const uint32_t cnbe_skill_table[CNBE_TABLE_SIZE] = {{\n")
        for i in range(0, len(all_rows), 8):
            chunk = [str(c) for _, c, _ in all_rows[i : i + 8]]
            fh.write("    " + ", ".join(chunk) + ",\n")
        fh.write("};\n")

    header = os.path.join(OUT_DIR, "cnbe_skill_table.h")
    with open(header, "w", encoding="ascii") as fh:
        fh.write("// Generated by tools/gen_skill_table.py from data/cnbe32.db\n")
        fh.write("// Deliberately repeatable: the Spike instruction template includes\n")
        fh.write("// this header inside multiple generated functions.\n")
        fh.write("#include <stdint.h>\n\n")
        fh.write(f"#define CNBE_TABLE_SIZE {len(all_rows)}u\n")
        fh.write("extern const uint32_t cnbe_unicode_table[CNBE_TABLE_SIZE];\n")
        fh.write("extern const uint32_t cnbe_skill_table[CNBE_TABLE_SIZE];\n\n")

    sv_params = os.path.join(OUT_DIR, "cnbe_table_params.svh")
    with open(sv_params, "w", encoding="ascii") as fh:
        fh.write("// Generated by tools/gen_skill_table.py\n")
        fh.write(f"localparam CNBE_TABLE_SIZE = {len(all_rows)};\n")

    summary = {
        "source_db": os.path.relpath(DB_PATH, V8_DIR),
        "total_rows": len(all_rows),
        "standard_rows": len(std_rows),
        "duplicate_cnbe": n_duplicates,
        "unicode_min": min(u for u, _, _ in all_rows),
        "unicode_max": max(u for u, _, _ in all_rows),
        "skill_table_bin_sha256": sha256_file(all_bin),
        "skill_table_8105_bin_sha256": sha256_file(std_bin),
        "files": {
            "skill_table.bin": all_bin,
            "skill_table_8105.bin": std_bin,
            "unicode_table.hex": unicode_hex,
            "cnbe_table.hex": cnbe_hex,
            "cnbe_skill_table.cc": cc_path,
            "cnbe_table_params.svh": sv_params,
        },
    }
    summary_path = os.path.join(OUT_DIR, "skill_table_summary.json")
    with open(summary_path, "w", encoding="utf-8") as fh:
        json.dump(summary, fh, ensure_ascii=False, indent=2)

    print(f"total={len(all_rows)} standard={len(std_rows)} duplicates={n_duplicates}")
    print(f"wrote {summary_path}")


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


if __name__ == "__main__":
    main()
