DECLARE_INSN(cnbe_map, MATCH_CNBE_MAP, MASK_CNBE_MAP)
DECLARE_INSN(cnbe_extract, MATCH_CNBE_EXTRACT, MASK_CNBE_EXTRACT)
DECLARE_INSN(cnbe_cmp, MATCH_CNBE_CMP, MASK_CNBE_CMP)
DECLARE_INSN(cnbe_skill, MATCH_CNBE_SKILL, MASK_CNBE_SKILL)
